################ Splash page #######################
[splash]
languageName = ""
contentDir = "content/splash"
weight = 1

################ English language ##################
[en]
languageName = "English"
languageCode = "en-CA"
contentDir = "content/en"
weight = 2

[fr]
languageName = "Fran√ßais"
languageCode = "fr-CA"
contentDir = "content/fr"
weight = 3
