############# English navigation ##############

# main menu
[[main]]
name = "GCDS Hugo"
pageRef = "/"
weight = 1
identifier = "home"

[[main]]
name = "About"
pageRef = "/about-us"
weight = 2

[[main]]
name = "Contact Us"
pageRef = "/contact"
weight = 3

[[main]]
weight = 4
name = "Examples"

  [[main]]
  parent = "Examples"
  name = "GCDS Components"
  pageRef = "/gcds-components"
